#ifndef _ANIM_TBL_H_
#define _ANIM_TBL_H_
//全部图档 以图标名字功能取名定位
/***********************************************************************
*	このファイルはコンバーターも通る
*
*	コンバーターは
*		#define SPRxxxxx　はxxxxxファイルを読み込もうとする。
*
*	sprファイルとしては  
*		#define		SPR_abc	1000
*	とあれば、
*		ファイル名	abc.spr
*	とする。
*	数字は一意であれば何でも可。
***********************************************************************/

//#define SPRSTART			30000		// SPRデータの始まりの番号 数据的* * * *开始的号码
#define SPRSTART			100000		// SPRデータの始まりの番号

// キャラ
#define SPR_001em			100000		//	子供男１	素手 100000
#define SPR_001ax			100001		// 			斧
#define SPR_001cl			100002		//			こん棒
#define SPR_001sp			100003		//			槍
#define SPR_001bw			100004		//			弓

#define SPR_002em			100005		//	子供男１	素手
#define SPR_002ax			100006		// 			斧
#define SPR_002cl			100007		//			こん棒
#define SPR_002sp			100008		//			槍
#define SPR_002bw			100009		//			弓

#define SPR_003em			100010		//	子供男１	素手
#define SPR_003ax			100011		// 			斧
#define SPR_003cl			100012		//			こん棒
#define SPR_003sp			100013		//			槍
#define SPR_003bw			100014		//			弓

#define SPR_004em			100015		//	子供男１	素手
#define SPR_004ax			100016		// 			斧
#define SPR_004cl			100017		//			こん棒
#define SPR_004sp			100018		//			槍
#define SPR_004bw			100019		//			弓

#define SPR_011em			100020		//	少年１		素手
#define SPR_011ax			100021		// 			斧
#define SPR_011cl			100022		//			こん棒
#define SPR_011sp			100023		//			槍
#define SPR_011bw			100024		//			弓

#define SPR_012em			100025		//	少年１		素手
#define SPR_012ax			100026		// 			斧
#define SPR_012cl			100027		//			こん棒
#define SPR_012sp			100028		//			槍
#define SPR_012bw			100029		//			弓

#define SPR_013em			100030		//	少年１		素手
#define SPR_013ax			100031		// 			斧
#define SPR_013cl			100032		//			こん棒
#define SPR_013sp			100033		//			槍
#define SPR_013bw			100034		//			弓

#define SPR_014em			100035		//	少年１		素手
#define SPR_014ax			100036		// 			斧
#define SPR_014cl			100037		//			こん棒
#define SPR_014sp			100038		//			槍
#define SPR_014bw			100039		//			弓

#define SPR_021em			100040		//	少年２		素手
#define SPR_021ax			100041		// 			斧
#define SPR_021cl			100042		//			こん棒
#define SPR_021sp			100043		//			槍
#define SPR_021bw			100044		//			弓

#define SPR_022em			100045
#define SPR_022ax			100046
#define SPR_022cl			100047
#define SPR_022sp			100048
#define SPR_022bw			100049

#define SPR_023em			100050
#define SPR_023ax			100051
#define SPR_023cl			100052
#define SPR_023sp			100053
#define SPR_023bw			100054

#define SPR_024em			100055
#define SPR_024ax			100056
#define SPR_024cl			100057
#define SPR_024sp			100058
#define SPR_024bw			100059

#define SPR_031em			100060		//	少年３		素手
#define SPR_031ax			100061		// 			斧
#define SPR_031cl			100062		//			こん棒
#define SPR_031sp			100063		//			槍
#define SPR_031bw			100064		//			弓

#define SPR_032em			100065
#define SPR_032ax			100066
#define SPR_032cl			100067
#define SPR_032sp			100068
#define SPR_032bw			100069

#define SPR_033em			100070
#define SPR_033ax			100071
#define SPR_033cl			100072
#define SPR_033sp			100073
#define SPR_033bw			100074

#define SPR_034em			100075
#define SPR_034ax			100076
#define SPR_034cl			100077
#define SPR_034sp			100078
#define SPR_034bw			100079

#define SPR_041em			100080		//	青年１		素手
#define SPR_041ax			100081		// 			斧
#define SPR_041cl			100082		//			こん棒
#define SPR_041sp			100083		//			槍
#define SPR_041bw			100084		//			弓

#define SPR_042em			100085
#define SPR_042ax			100086
#define SPR_042cl			100087
#define SPR_042sp			100088
#define SPR_042bw			100089

#define SPR_043em			100090
#define SPR_043ax			100091
#define SPR_043cl			100092
#define SPR_043sp			100093
#define SPR_043bw			100094

#define SPR_044em			100095
#define SPR_044ax			100096
#define SPR_044cl			100097
#define SPR_044sp			100098
#define SPR_044bw			100099

#define SPR_051em			100100		//	青年２		素手
#define SPR_051ax			100101		// 			斧
#define SPR_051cl			100102		//			こん棒
#define SPR_051sp			100103		//			槍
#define SPR_051bw			100104		//			弓

#define SPR_052em			100105
#define SPR_052ax			100106
#define SPR_052cl			100107
#define SPR_052sp			100108
#define SPR_052bw			100109

#define SPR_053em			100110
#define SPR_053ax			100111
#define SPR_053cl			100112
#define SPR_053sp			100113
#define SPR_053bw			100114

#define SPR_054em			100115
#define SPR_054ax			100116
#define SPR_054cl			100117
#define SPR_054sp			100118
#define SPR_054bw			100119

#define SPR_061em			100120		//	子供女１		素手
#define SPR_061ax			100121		// 			斧
#define SPR_061cl			100122		//			こん棒
#define SPR_061sp			100123		//			槍
#define SPR_061bw			100124		//			弓

#define SPR_062em			100125
#define SPR_062ax			100126
#define SPR_062cl			100127
#define SPR_062sp			100128
#define SPR_062bw			100129

#define SPR_063em			100130
#define SPR_063ax			100131
#define SPR_063cl			100132
#define SPR_063sp			100133
#define SPR_063bw			100134

#define SPR_064em			100135
#define SPR_064ax			100136
#define SPR_064cl			100137
#define SPR_064sp			100138
#define SPR_064bw			100139

#define SPR_071em			100140		//	少女１１	素手
#define SPR_071ax			100141		// 			斧
#define SPR_071cl			100142		//			こん棒
#define SPR_071sp			100143		//			槍
#define SPR_071bw			100144		//			弓

#define SPR_072em			100145
#define SPR_072ax			100146
#define SPR_072cl			100147
#define SPR_072sp			100148
#define SPR_072bw			100149

#define SPR_073em			100150
#define SPR_073ax			100151
#define SPR_073cl			100152
#define SPR_073sp			100153
#define SPR_073bw			100154

#define SPR_074em			100155
#define SPR_074ax			100156
#define SPR_074cl			100157
#define SPR_074sp			100158
#define SPR_074bw			100159

#define SPR_081em			100160		//	少女２		素手
#define SPR_081ax			100161		// 			斧
#define SPR_081cl			100162		//			こん棒
#define SPR_081sp			100163		//			槍
#define SPR_081bw			100164		//			弓

#define SPR_082em			100165
#define SPR_082ax			100166
#define SPR_082cl			100167
#define SPR_082sp			100168
#define SPR_082bw			100169

#define SPR_083em			100170
#define SPR_083ax			100171
#define SPR_083cl			100172
#define SPR_083sp			100173
#define SPR_083bw			100174

#define SPR_084em			100175
#define SPR_084ax			100176
#define SPR_084cl			100177
#define SPR_084sp			100178
#define SPR_084bw			100179

#define SPR_091em			100180		//	少女３		素手
#define SPR_091ax			100181		// 			斧
#define SPR_091cl			100182		//			こん棒
#define SPR_091sp			100183		//			槍
#define SPR_091bw			100184		//			弓

#define SPR_092em			100185
#define SPR_092ax			100186
#define SPR_092cl			100187
#define SPR_092sp			100188
#define SPR_092bw			100189

#define SPR_093em			100190
#define SPR_093ax			100191
#define SPR_093cl			100192
#define SPR_093sp			100193
#define SPR_093bw			100194

#define SPR_094em			100195
#define SPR_094ax			100196
#define SPR_094cl			100197
#define SPR_094sp			100198
#define SPR_094bw			100199

#define SPR_101em			100200		//	女性１		素手
#define SPR_101ax			100201		// 			斧
#define SPR_101cl			100202		//			こん棒
#define SPR_101sp			100203		//			槍
#define SPR_101bw			100204		//			弓

#define SPR_102em			100205
#define SPR_102ax			100206
#define SPR_102cl			100207
#define SPR_102sp			100208
#define SPR_102bw			100209

#define SPR_103em			100210
#define SPR_103ax			100211
#define SPR_103cl			100212
#define SPR_103sp			100213
#define SPR_103bw			100214

#define SPR_104em			100215
#define SPR_104ax			100216
#define SPR_104cl			100217
#define SPR_104sp			100218
#define SPR_104bw			100219

#define SPR_111em			100220		//	女性２		素手
#define SPR_111ax			100221		// 			斧
#define SPR_111cl			100222		//			こん棒
#define SPR_111sp			100223		//			槍
#define SPR_111bw			100224		//			弓

#define SPR_112em			100225
#define SPR_112ax			100226
#define SPR_112cl			100227
#define SPR_112sp			100228
#define SPR_112bw			100229

#define SPR_113em			100230
#define SPR_113ax			100231
#define SPR_113cl			100232
#define SPR_113sp			100233
#define SPR_113bw			100234

#define SPR_114em			100235
#define SPR_114ax			100236
#define SPR_114cl			100237
#define SPR_114sp			100238
#define SPR_114bw			100239


// ペット（敵）キャラ  敌人
#define SPR_pet001			100250		//	ウーリ
#define SPR_pet002			100251		//	ウリウリ
#define SPR_pet003			100252		//	ウリスタイン
#define SPR_pet004			100253		//	ウリブル

#define SPR_pet011			100254		//	ブービィ
#define SPR_pet012			100255		//	ゴールドブーイ
#define SPR_pet013			100256		//	ブーイ
#define SPR_pet014			100257		//	ブイービー
#define SPR_pet015			100258		//	カーブイ

#define SPR_pet021			100259		//	ギャミー
#define SPR_pet022			100260		//	ギャビー
#define SPR_pet023			100261		//	ギャビオ
#define SPR_pet024			100262		//	ギャース

#define SPR_pet031			100263		//	ウポポ
#define SPR_pet032			100264		//	ウィウィ
#define SPR_pet033			100265		//	ウガルー
#define SPR_pet034			100266		//	ウィーバ

#define SPR_pet041			100267		//	ベローン
#define SPR_pet042			100268		//	ベロロック
#define SPR_pet043			100269		//	ベロポックル
#define SPR_pet044			100270		//	ベロポリ

#define SPR_pet051			100271		//	カメノドン
#define SPR_pet052			100272		//	カラゴ
#define SPR_pet053			100273		//	ヤドカメ
#define SPR_pet054			100274		//	カラゴル

#define SPR_pet061			100275		//	ネゴス
#define SPR_pet062			100276		//	ネギャス
#define SPR_pet063			100277		//	タロゴン
#define SPR_pet064			100278		//	ダックル

#define SPR_pet071			100279		//	ラギルゴ
#define SPR_pet072			100280		//	フババ
#define SPR_pet073			100281		//	トサキング
#define SPR_pet074			100282		//	ルニテス

#define SPR_pet081			100283		//	ルニテス
#define SPR_pet082			100284		//	カタルカス
#define SPR_pet083			100285		//	クイッタ
#define SPR_pet084			100286		//	コロギャス

#define SPR_pet091			100287		//	リゼノドン
#define SPR_pet092			100288		//	ヤンギロス
#define SPR_pet093			100289		//	バンボロス
#define SPR_pet094			100290		//	バンギーノ

#define SPR_pet101			100291		//	クレル
#define SPR_pet102			100292		//	ククル
#define SPR_pet103			100293		//	キョロル
#define SPR_pet104			100294		//	リスキー

#define SPR_pet111			100295		//	カビット
#define SPR_pet112			100296		//	ケイビー
#define SPR_pet113			100297		//	キューイ
#define SPR_pet114			100298		//	キャビット

#define SPR_pet121			100299		//	なし
#define SPR_pet122			100300		//	なし
#define SPR_pet123			100301		//	なし
#define SPR_pet124			100302		//	なし

#define SPR_pet131			100303		//	なし
#define SPR_pet132			100304		//	なし
#define SPR_pet133			100305		//	なし
#define SPR_pet134			100306		//	なし

#define SPR_pet141			100307		//	ゴルドン
#define SPR_pet142			100308		//	ギラドン
#define SPR_pet143			100309		//	ギラゴルゴン
#define SPR_pet144			100310		//	ゴルーゴ

#define SPR_pet151			100311		//	なし
#define SPR_pet152			100312		//	なし
#define SPR_pet153			100313		//	なし
#define SPR_pet154			100314		//	なし

#define SPR_pet161			100315		//	なし
#define SPR_pet162			100316		//	なし
#define SPR_pet163			100317		//	なし
#define SPR_pet164			100318		//	なし

#define SPR_pet171			100319		//	ヒューボ
#define SPR_pet172			100320		//	ガラボス
#define SPR_pet173			100321		//	プクプク
#define SPR_pet174			100322		//	トロージャ

#define SPR_pet181			100323		//	ホロール
#define SPR_pet182			100324		//	ククール
#define SPR_pet183			100325		//	ルババ
#define SPR_pet184			100326		//	クルーバ

#define SPR_pet191			100327		//	ベルガー
#define SPR_pet192			100328		//	ベルイガー
#define SPR_pet193			100329		//	ゴルシス
#define SPR_pet194			100330		//	キングサーベル

#define SPR_pet201			100331		//	なし
#define SPR_pet202			100332		//	なし
#define SPR_pet203			100333		//	なし
#define SPR_pet204			100334		//	なし

#define SPR_pet211			100335		//	トリノプス
#define SPR_pet212			100336		//	ペンタス
#define SPR_pet213			100337		//	トリケラー
#define SPR_pet214			100338		//	トロプス

#define SPR_pet221			100339		//	コバンケス
#define SPR_pet222			100340		//	ジャグラ
#define SPR_pet223			100341		//	ジャーグ
#define SPR_pet224			100342		//	バンジー

#define SPR_pet231			100343		//	ギガロス
#define SPR_pet232			100344		//	ギーナ
#define SPR_pet233			100345		//	ギガンボス
#define SPR_pet234			100346		//	ガガギンボ

#define SPR_pet241			100347		//	パーキー
#define SPR_pet242			100348		//	ムーイー
#define SPR_pet243			100349		//	シボーズ
#define SPR_pet244			100350		//	トルーポー

#define SPR_pet251			100351		//	ブロントス
#define SPR_pet252			100352		//	ブリンテス
#define SPR_pet253			100353		//	ブラキトス
#define SPR_pet254			100354		//	ステントス

#define SPR_pet261			100355		//	マンモー
#define SPR_pet262			100356		//	ンモモ
#define SPR_pet263			100357		//	マモナス
#define SPR_pet264			100358		//	マンモロス

#define SPR_pet271			100359		//	テラゴン
#define SPR_pet272			100360		//	ノガロン
#define SPR_pet273			100361		//	ジャバゴン
#define SPR_pet274			100362		//	ドラピス

#define SPR_pet281			100363		//	なし
#define SPR_pet282			100364		//	なし
#define SPR_pet283			100365		//	なし
#define SPR_pet284			100366		//	なし

#define SPR_pet291			100367		//	タッキー
#define SPR_pet292			100368		//	ククロス
#define SPR_pet293			100369		//	ホルック
#define SPR_pet294			100370		//	キィーボー

#define SPR_pet301			100371		//	オガロス
#define SPR_pet302			100372		//	ゾディノス
#define SPR_pet303			100373		//	パドラン
#define SPR_pet304			100374		//	テラゾイド

#define SPR_pet311			100375		//	プイト
#define SPR_pet312			100376		//	モナシープ
#define SPR_pet313			100377		//	カイホーン
#define SPR_pet314			100378		//	ライホーン

#define SPR_pet321			100379		//	ストラジドン
#define SPR_pet322			100380		//	ザメロス
#define SPR_pet323			100381		//	アリゲノス
#define SPR_pet324			100382		//	ダイノロス
#define SPR_pet325			100383		//	ラコロス

#define SPR_pet331			100384		//	バロロクス
#define SPR_pet332			100385		//	ランベルス
#define SPR_pet333			100386		//	コリトロス
#define SPR_pet334			100387		//	ノーストロス

// 新規追加ペット
#define SPR_pet005			100388		//	黒瓜
#define SPR_pet085			100389		//	岩カタルカス
#define SPR_pet086			100390		//	氷クイッタ
#define SPR_pet087			100391		//	ブラックコロギャス
#define SPR_pet088			100392		//	アスファルトロギアン
#define SPR_pet065			100393		//	風属性ネゴス
#define SPR_pet095			100394		//	風属性リゼノドン
#define SPR_pet175			100395		//	風属性ビューボ
#define SPR_pet255			100396		//	風属性ブロントス

// 新規追加プレイヤーキャラ
#define SPR_121em			100400		//	アフロ１	素手
#define SPR_121ax			100401		//			斧
#define SPR_121cl			100402		//			棍棒
#define SPR_121sp			100403		//			槍
#define SPR_121bw			100404		//			弓

#define SPR_122em			100405		//	アフロ２	素手
#define SPR_122ax			100406		//			斧
#define SPR_122cl			100407		//			棍棒
#define SPR_122sp			100408		//			槍
#define SPR_122bw			100409		//			弓

#define SPR_123em			100410		//	アフロ３	素手
#define SPR_123ax			100411		//			斧
#define SPR_123cl			100412		//			棍棒
#define SPR_123sp			100413		//			槍
#define SPR_123bw			100414		//			弓

#define SPR_124em			100415		//	アフロ４	素手
#define SPR_124ax			100416		//			斧
#define SPR_124cl			100417		//			棍棒
#define SPR_124sp			100418		//			槍
#define SPR_124bw			100419		//			弓

#define SPR_131em			100420		//	ＪＳＳ１	素手
#define SPR_131ax			100421		//			斧
#define SPR_131cl			100422		//			棍棒
#define SPR_131sp			100423		//			槍
#define SPR_131bw			100424		//			弓

#define SPR_132em			100425		//	ＪＳＳ２	素手
#define SPR_132ax			100426		//			斧
#define SPR_132cl			100427		//			棍棒
#define SPR_132sp			100428		//			槍
#define SPR_132bw			100429		//			弓

#define SPR_pet315			100430		//	パンダホーン

#define SPR_141em			100431		//	ゲンさん１	素手
#define SPR_141ax			100432		//			斧
#define SPR_141cl			100433		//			棍棒
#define SPR_141sp			100434		//			槍
#define SPR_141bw			100435		//			弓

#define SPR_142em			100436		//	ゲンさん２	素手
#define SPR_142ax			100437		//			斧
#define SPR_142cl			100438		//			棍棒
#define SPR_142sp			100439		//			槍
#define SPR_142bw			100440		//			弓

#define SPR_133em			100441		//	ＪＳＳ３	素手
#define SPR_133ax			100442		//			斧
#define SPR_133cl			100443		//			棍棒
#define SPR_133sp			100444		//			槍
#define SPR_133bw			100445		//			弓

#define SPR_151em			100446		//	少女１５	素手
#define SPR_151ax			100447		// 			斧
#define SPR_151cl			100448		//			こん棒
#define SPR_151sp			100449		//			槍
#define SPR_151bw			100450		//			弓

#define SPR_152em			100451
#define SPR_152ax			100452
#define SPR_152cl			100453
#define SPR_152sp			100454
#define SPR_152bw			100455

#define SPR_161em			100456		//	少女１６	素手
#define SPR_161ax			100457		// 			斧
#define SPR_161cl			100458		//			こん棒
#define SPR_161sp			100459		//			槍
#define SPR_161bw			100460		//			弓

#define SPR_162em			100461
#define SPR_162ax			100462
#define SPR_162cl			100463
#define SPR_162sp			100464
#define SPR_162bw			100465

//木　及び　石モンスター
#define SPR_mwood1			100466
#define SPR_mwood2			100467
#define SPR_mwood3			100468
#define SPR_mstone1			100469
#define SPR_mstone2			100470
#define SPR_mstone3			100471

//各種アニメーション
#define SPR_leader			100500		//	リーダーマークアニメーション
#define SPR_star			100501		//	ぴよぴよの星マークアニメ
#define SPR_boomerang		100502		//	ブーメランのアニメーション
#define SPR_stornbomb		100503		//	石の砕けアニメーション
#define SPR_ono				100504		//	投げ斧アニメーション
#define SPR_onokage			100505		//	投げ斧の影けアニメーション
#define SPR_isiware			100506		//	石割れアニメーション
#define SPR_mail			100507		//	メール着信アニメーション
//効果アニメ
#define SPR_stone			100550		//	石化効果アニメ
#define SPR_shock			100551		//	麻痺効果アニメ
#define SPR_drunk			100552		//	酔い効果アニメ
#define SPR_sleep			100553		//	眠り効果アニメ
#define SPR_conf			100554		//	混乱効果アニメ
#define SPR_poison			100555		//	毒効果アニメ
#define SPR_zokusei			100556		//	属性変換効果アニメ
//呪術エフェクトアニメーション 念咒效果动画
#define SPR_effect01		100600		//	呪術アニメーション
#define SPR_heal			100601		//	呪術アニメーション（回復１）
#define SPR_heal2			100602		//	呪術アニメーション（回復２）
#define SPR_heal3			100603		//	呪術アニメーション（回復３）
#define SPR_tyusya			100604		//	呪術アニメーション（ステータス異常回復）
#define SPR_hoshi			100605		//	呪術をかけられたときのアニメーション
#define SPR_kyu				100606		//	ステータス回復呪術をかけられたときのアニメーション
#define SPR_fukkatu1		100607		//	復活（１）をかけられたときのアニメーション
#define SPR_fukkatu2		100608		//	復活（２）をかけられたときのアニメーション
#define SPR_fukkatu3		100609		//	復活（３）をかけられたときのアニメーション
#define SPR_difence			100610		//	防御系呪術をかけられたときのアニメーション
#define SPR_item			100611		//	アイテムを使用したときのアニメーション
#define SPR_item3			100612		//	アイテムを使用したときのアニメーション
//防御系呪術アニメーション
#define SPR_mirror			100650		//	反射アニメーション
#define SPR_barrior			100651		//	バリアアニメーション
#define SPR_kyusyu			100652		//	吸収したときのアニメーション

// ここからは、ＳＰＲデータではない ******* 从这里，SPR数据。*********************************************/
#define CG_INVISIBLE				99	// これ以下は画面に描画されない  这以下画面被描画。
//#define CG_GRID_CURSOR		99
#define CG_MOUSE_CURSOR		24316    //鼠标25000
#define CG_GRID_CURSOR		25001    //

// プレイヤーのバトルボタン  玩家战斗按钮
#define CG_BTL_BUTTON_ATTACK_UP		25100
#define CG_BTL_BUTTON_ATTACK_DOWN	25101
#define CG_BTL_BUTTON_JUJUTU_UP		25102
#define CG_BTL_BUTTON_JUJUTU_DOWN	25103
#define CG_BTL_BUTTON_CAPTURE_UP	25104
#define CG_BTL_BUTTON_CAPTURE_DOWN	25105
#define CG_BTL_BUTTON_HELP_UP		25106
#define CG_BTL_BUTTON_HELP_DOWN		25107
#define CG_BTL_BUTTON_GUARD_UP		25108
#define CG_BTL_BUTTON_GUARD_DOWN	25109
#define CG_BTL_BUTTON_ITEM_UP		25110
#define CG_BTL_BUTTON_ITEM_DOWN		25111
#define CG_BTL_BUTTON_PET_UP		25112
#define CG_BTL_BUTTON_PET_DOWN		25113
#define CG_BTL_BUTTON_ESCAPE_UP		25114
#define CG_BTL_BUTTON_ESCAPE_DOWN	25115
#define CG_BTL_BUTTON_BASE			25116	// ボタンの土台
#define CG_BTL_BUTTON_CROSS			25117	// ×ボタン

// 属性アイコン
#define CG_ATR_ICON_EARTH_BIG		25120	// 「地」大
#define CG_ATR_ICON_EARTH_MDL		25121	// 「地」中
#define CG_ATR_ICON_EARTH_SML		25122	// 「地」小
#define CG_ATR_ICON_WATER_BIG		25123	// 「水」大
#define CG_ATR_ICON_WATER_MDL		25124	// 「水」中
#define CG_ATR_ICON_WATER_SML		25125	// 「水」小
#define CG_ATR_ICON_FIRE_BIG		25126	// 「火」大
#define CG_ATR_ICON_FIRE_MDL		25127	// 「火」中
#define CG_ATR_ICON_FIRE_SML		25128	// 「火」小
#define CG_ATR_ICON_WIND_BIG		25129	// 「風」大
#define CG_ATR_ICON_WIND_MDL		25130	// 「風」中
#define CG_ATR_ICON_WIND_SML		25131	// 「風」小

// 戦闘中属性アイコン
#define CG_ATR_ICON_EARTH_BATTLE	25132	// 「地」
#define CG_ATR_ICON_WATER_BATTLE	25133	// 「水」
#define CG_ATR_ICON_FIRE_BATTLE		25134	// 「火」
#define CG_ATR_ICON_WIND_BATTLE		25135	// 「風」

// ペットのバトルボタン
#define CG_PET_BTL_BUTTON_BASE		25140	// ボタンの土台
#define CG_PET_BTL_BUTTON_WAZA_UP	25141	// 技ボタン凸
#define CG_PET_BTL_BUTTON_WAZA_DOWN	25142	// 技ボタン凹
#define CG_PET_BTL_BUTTON_CANCEL_UP	25143	// キャンセルボタン凸

// ヒットマーク
#define CG_HIT_MARK_00				25500	// 星大
#define CG_HIT_MARK_01				25501	// 星小

#define CG_HIT_MARK_10				25502	// 青色
#define CG_HIT_MARK_11				25503
#define CG_HIT_MARK_12				25504

#define CG_HIT_MARK_20				25505	// 赤色
#define CG_HIT_MARK_21				25506
#define CG_HIT_MARK_22				25507

#define CG_HIT_MARK_30				25508	// 水色
#define CG_HIT_MARK_31				25509
#define CG_HIT_MARK_32				25510

#define CG_HIT_MARK_40				25511	// 黄色
#define CG_HIT_MARK_41				25512
#define CG_HIT_MARK_42				25513

// 台詞
#define CG_SPEECH_BTL_OK			25520
#define CG_SPEECH_CHANGE			25521
#define CG_SPEECH_GROUP				25522
#define CG_SPEECH_SUCCESS			25523
#define CG_SPEECH_YATTA				25524
#define CG_SPEECH_HELP				25525

// エンカウントマーク  遇敌标志
#define CG_VS_MARK_1A				25610
#define CG_VS_MARK_1B				25611
#define CG_VS_MARK_2A				25612
#define CG_VS_MARK_2B				25613
#define CG_VS_MARK_3A				25614
#define CG_VS_MARK_3B				25615
#define CG_VS_MARK_4A				25616
#define CG_VS_MARK_4B				25617
#define CG_VS_MARK_5A				25618
#define CG_VS_MARK_5B				25619
#define CG_VS_MARK_6A				25620
#define CG_VS_MARK_6B				25621
#define CG_VS_MARK_7A				25622
#define CG_VS_MARK_7B				25623
#define CG_VS_MARK_8A				25624
#define CG_VS_MARK_8B				25625
#define CG_VS_MARK_9A				25626
#define CG_VS_MARK_9B				25627
#define CG_VS_MARK_10A				25628
#define CG_VS_MARK_10B				25629

// 弓矢
#define CG_ARROW_00					25630
#define CG_ARROW_01					25631
#define CG_ARROW_02					25632
#define CG_ARROW_03					25633
#define CG_ARROW_04					25634
#define CG_ARROW_05					25635
#define CG_ARROW_06					25636
#define CG_ARROW_07					25637
#define CG_ARROW_08					25638
#define CG_ARROW_09					25639
#define CG_ARROW_10					25640
#define CG_ARROW_11					25641
#define CG_ARROW_12					25642
#define CG_ARROW_13					25643
#define CG_ARROW_14					25644
#define CG_ARROW_15					25645

// カウントダウン数字  倒计时的数字
#define CG_CNT_DOWN_0				25900
#define CG_CNT_DOWN_1				25901
#define CG_CNT_DOWN_2				25902
#define CG_CNT_DOWN_3				25903
#define CG_CNT_DOWN_4				25904
#define CG_CNT_DOWN_5				25905
#define CG_CNT_DOWN_6				25906
#define CG_CNT_DOWN_7				25907
#define CG_CNT_DOWN_8				25908
#define CG_CNT_DOWN_9   			25909

// 汎用ウィンドウ  通用窗口
#define CG_WND_G_0			26001
#define CG_WND_G_1			26002
#define CG_WND_G_2			26003
#define CG_WND_G_3			26004
#define CG_WND_G_4			26005  //图片损坏还是什么出不来
#define CG_WND_G_5			26006
#define CG_WND_G_6			26007
#define CG_WND_G_7			26008
#define CG_WND_G_8			26009

// ウィンドウタイトル   窗口标题
#define CG_WND_TITLE_SYSTEM	26010  //系统  
#define CG_WND_TITLE_LOGOUT	26011
#define CG_WND_TITLE_CHAT	26015  //聊天设定
#define CG_WND_TITLE_BGM	26016  //背景音乐
#define CG_WND_TITLE_SE		26017
#define CG_WND_TITLE_RESULT	26018

// タスクバー
#define CG_TASK_BAR_BACK		26012

// 戦闘時のＨＰとＭＰバー
#define CG_BATTLE_BAR_PLAYER		26013	// プレイヤー
#define CG_BATTLE_BAR_PLAYER_2		26019	// プレイヤー
#define CG_BATTLE_BAR_PET			26014	// 他の人
#define CG_BATTLE_BAR_PET_2			26020	// プレイヤーのペット

// 汎用ウィンドウ２  通用窗口2
#define CG_WND2_G_0			26021
#define CG_WND2_G_1			26022
#define CG_WND2_G_2			26023
#define CG_WND2_G_3			26024
#define CG_WND2_G_4			26025
#define CG_WND2_G_5			26026
#define CG_WND2_G_6			26027
#define CG_WND2_G_7			26028
#define CG_WND2_G_8			26029

// 汎用ウィンドウ３  通用窗口
#define CG_WND3_G_7			26037	// 下のみ、文字を打ち込めるタイプ
#define CG_WND3_G_8			26038
#define CG_WND3_G_9			26039

// 本物ウィンドウ  真正的窗口
#define CG_BTL_PET_CHANGE_WND	26040	// 戦闘時のペット入れ替えウィンドウ
#define CG_BTL_PET_RETURN_BTN	26041	// 戦闘時のペット戻すボタン（汎用）

// 汎用ボタン
#define CG_CLOSE_BTN			26042	// 閉じるボタン（汎用）
#define CG_RETURN_BTN			26043	// 戻るボタン（汎用）
#define CG_OK_BTN				26093	// ＯＫボタン（汎用）
#define CG_CANCEL_BTN			26050	// キャンセルボタン（汎用）

#define CG_YES_BTN				26094	// はい"ボタン  是”按钮
#define CG_NO_BTN				26095	// "いいえ"ボタン  不是
#define CG_EXIT_BTN				26096	// "?}""出る"ボタン  出去
#define CG_SEAL_BTN				26097	// "?讌X""売る"ボタン 买
#define CG_BUY_BTN				26098	// "?R?i""買う"ボタン 卖

// ペットウィンドウ  宠物窗口
#define CG_PET_WND_VIEW			26044	// ペットステータス一覧ウィンドウ  宠物属性一览窗口
#define CG_PET_WND_DETAIL		26045	// ペットの詳細ウィンドウ  宠物的详细窗口

#define CG_PET_WND_WAZA_BTN		26046	// 技ボタン（汎用）  宠物技能按钮（通用
//#define CG_PREV_BTN				26047	// 前に切り替えるボタン（汎用）
//#define CG_NEXT_BTN				26048	// 次に切り替えるボタン（汎用）
#define CG_NAME_CHANGE_WND		26049	// 名前変更ウィンドウ  更改姓名
//#define CG_NAME_CHANGE_BTN		26051	// 名前変更ボタン
#define CG_NAME_CHANGE_BTN		26058	// 名前変更ボタン凸  更改姓名
#define CG_NAME_CHANGE_BTN_DOWN	26059	// 名前変更ボタン凹

#define CG_PET_WND_REST_BTN		26052	// ペット休みボタン  宠物休息
#define CG_PET_WND_STANDBY_BTN	26053	// ペット待機ボタン  战斗
#define CG_PET_WND_BTL_BTN		26054	// ペットバトルボタン   等待
#define CG_PET_WND_MAIL_BTN		26055	// ペットメールボタン  邮件
#define CG_PET_WND_STATUS_BTN	26056	// ペット詳細ボタン   状态


// アイテムウィンドウ  物品窗口
#define CG_ITEM_WND_0		26060	// アイテムウィンドウ上
#define CG_ITEM_WND_1		26061	// アイテムウィンドウ下
#define CG_ITEM_WND_GOLD_DROP_BTN_UP	26062	// お金落とすボタン凸
#define CG_ITEM_WND_GOLD_DROP_BTN_DOWN	26063	// お金落とすボタン凹
#define CG_ITEM_WND_GOLD_INC_BTN_UP		26064	// お金増やすボタン凸
#define CG_ITEM_WND_GOLD_INC_BTN_DOWN	26065	// お金増やすボタン凹
#define CG_ITEM_WND_GOLD_DEC_BTN_UP		26066	// お金減らすボタン凸
#define CG_ITEM_WND_GOLD_DEC_BTN_DOWN	26067	// お金減らすボタン凹
#define CG_JUJUTU_WND					26068	// 呪術ウィンドウ
#define CG_ITEM_WND_JUJUTU_BTN			26069	// アイテムウィンドウの呪術ボタン
#define CG_ITEM_WND_SELECT_WND			26070	// 選択ウィンドウ
#define CG_STATUS_WND_GROUP_WND			26071	// ステータス一覧ウィンドウ
#define CG_BTL_ITEM_WND_TITLE			26072	// 戦闘時のアイテムウィンドウタイトル

// ステータスウィンドウ
#define CG_STATUS_WND					26073	// プレイヤーステータスウィンドウ
#define CG_STATUS_WND_VICTORY_MARK		26074	// 連勝マーク
#define CG_STATUS_WND_LV_UP_POINT		26075	// レベルアップ文字
#define CG_STATUS_WND_UP_BTN_UP			26076	// ステータスアップボタン凸
#define CG_STATUS_WND_UP_BTN_DOWN		26077	// ステータスアップボタン凹
#define CG_STATUS_WND_SHOUGOU_BTN_UP	26078	// 称号ボタン凸
#define CG_STATUS_WND_SHOUGOU_BTN_DOWN	26079	// 称号ボタン凹
#define CG_STATUS_WND_GROUP_BTN			26080	// グループ一覧ボタン

// マップウィンドウ
#define CG_MAP_WND						26081	// マップウィンドウ

// メールウィンドウ
#define CG_MAIL_WND						26082	// メールウィンドウ
#define CG_MAIL_WND_SEND_WND			26200	// メール送信ウィンドウ
#define CG_MAIL_WND_PET_SEND_WND		26201	// メールとペット送信ウィンドウ
#define CG_MAIL_WND_ITEM_BTN			26202	// アイテムボタン
#define CG_MAIL_WND_HISTORY_WND			26203	// メール履歴ウィンドウ

//#define CG_MAIL_WND_MAIL_BTN			26083	// メールボタン
#define CG_MAIL_WND_ON_LINE_SUN_BTN		26084	// ＯＮラインボタン「ＳＵＮ」
#define CG_MAIL_WND_ON_LINE_MOON_BTN	26088	// ＯＮラインボタン「ＭＯＯＮ」
#define CG_MAIL_WND_OFF_LINE_BTN		26085	// ＯＦＦラインボタン
#define CG_MAIL_WND_MAIL_BTN			26086	// 履歴ボタン
#define CG_MAIL_WND_DELETE_BTN			26087	// 削除ボタン
#define CG_MAIL_WND_CLEAR_BTN_UP		26172	// 文章クリアボタン凸
#define CG_MAIL_WND_CLEAR_BTN_DOWN		26173	// 文章クリアボタン凹
#define CG_SEND_BTN						26099	// "?e?H""送信"ボタン凸
#define CG_SEND_BTN_DOWN				26174	// "?e?H""送信"ボタン凹

// アルバムウィンドウ
#define CG_ALBUM_WND					26230	// アルバムウィンドウ
#define CG_ALBUM_WND_NEW_ICON			26231	// 新規アイコン
#define CG_ALBUM_WND_SNAP_BTN_UP		26170	// 写真を撮る凸
#define CG_ALBUM_WND_SNAP_BTN_DOWN		26171	// 写真を撮る凹

// チャットの文字登録ウィンドウ
#define CG_CHAT_REGISTY_WND				26232

// 文字入り汎用ウィンドウ
#define CG_COMMON_WIN_YORO				26090	// "?o???i?H?F???H""よろしいですか"と書かれたウィンドウ
#define CG_COMMON_YES_BTN				26091	// はいボタン
#define CG_COMMON_NO_BTN				26092	// いいえボタン

// フィールド画面ボタン類
#define CG_FIELD_MENU_LEFT				26100	// 左上台座
#define CG_FIELD_MENU_BTN_OFF			26101	// メニューボタンオフ状態
#define CG_FIELD_MENU_BTN_ON			26102	// メニューボタンオン状態
#define CG_FIELD_CARD_BTN_OFF			26103	// 名刺ボタンオフ状態
#define CG_FIELD_CARD_BTN_ON			26104	// 名刺ボタンオン状態
#define CG_FIELD_GROUP_BTN_OFF			26105	// グループボタンオフ状態
#define CG_FIELD_GROUP_BTN_ON			26106	// グループボタンオン状態
#define CG_FIELD_MAIL_LAMP				26107	// メール受信ランプ
#define CG_FIELD_MENU_RIGHT				26110	// 右上台座
#define CG_FIELD_JOIN_BTL_BTN_OFF		26111	// 参戦ボタンオフ状態
#define CG_FIELD_JOIN_BTL_BTN_ON		26112	// 参戦ボタンオン状態
#define CG_FIELD_DUEL_BTN_OFF			26113	// 対戦ボタンオフ状態
#define CG_FIELD_DUEL_BTN_ON			26114	// 対戦ボタンオン状態
#define CG_FIELD_ACT_BTN_OFF			26115	// アクションボタンオフ状態
#define CG_FIELD_ACT_BTN_ON				26116	// アクションボタンオン状態
#define CG_FIELD_AM_PM_00				26117	// 朝?夜グラフィック
#define CG_FIELD_AM_PM_01				26118	// 朝?夜グラフィック
#define CG_FIELD_AM_PM_02				26119	// 朝?夜グラフィック
#define CG_FIELD_AM_PM_03				26120	// 朝?夜グラフィック
#define CG_FIELD_MENU_RIGHT_BACK		26121	// 右上台座のバック

// ペットの技ウィンドウ
#define CG_PET_WAZA_WND		26130
#define CG_PET_WAZA_BAR_1	26131
#define CG_PET_WAZA_BAR_2	26132
#define CG_PET_WAZA_BAR_3	26133
#define CG_PET_WAZA_BAR_4	26134
#define CG_PET_WAZA_BAR_5	26135
#define CG_PET_WAZA_BAR_6	26136
#define CG_PET_WAZA_BAR_7	26137

// アイテムショップウィンドウ
#define CG_ITEMSHOP_WIN			26138

// 技ショップウィンドウ
#define CG_SKILLSHOP_WIN		26139

// まとめ買いウィンドウ
#define CG_ITEMSHOP_KOSU_WIN	26140

// タスクバーボタン
#define CG_TASK_BAR_MAP_UP		26150
#define CG_TASK_BAR_MAP_DOWM	26151
#define CG_TASK_BAR_STATUS_UP	26152
#define CG_TASK_BAR_STATUS_DOWN	26153
#define CG_TASK_BAR_PET_UP		26154
#define CG_TASK_BAR_PET_DOWN	26155
#define CG_TASK_BAR_ITEM_UP		26156
#define CG_TASK_BAR_ITEM_DOWN	26157
#define CG_TASK_BAR_MAIL_UP		26158
#define CG_TASK_BAR_MAIL_DOWN	26159
#define CG_TASK_BAR_ALBUM_UP	26160
#define CG_TASK_BAR_ALBUM_DOWN	26161
#define CG_TASK_BAR_SYSTEM_UP	26162
#define CG_TASK_BAR_SYSTEM_DOWN	26163

// 前後ボタン  前后按钮
#define CG_PREV_BTN				26180	// ＜ボタン凸 左箭头
#define CG_PREV_BTN_DOWN		26181	// ＜ボタン凹
#define CG_NEXT_BTN				26182	// ＞ボタン凸
#define CG_NEXT_BTN_DOWN		26183	// ＞ボタン凹

#define CG_PREV_BTN2			26184	// ?ボタン凸
#define CG_PREV_BTN2_DOWN		26185	// ?ボタン凹
#define CG_NEXT_BTN2			26186	// ?ボタン凸
#define CG_NEXT_BTN2_DOWN		26187	// ?ボタン凹

#define CG_UP_BTN				26188	// ▲ボタン凸
#define CG_UP_BTN_DOWN			26189	// ▲ボタン凹
#define CG_DOWN_BTN				26190	// ▼ボタン凸
#define CG_DOWN_BTN_DOWN		26191	// ▼ボタン凹


// アイコン  图标
#define CG_ICON_FUKIDASI		26500	// チャット入力時後の吹き出し  聊天输入时后的出来了
#define CG_ICON_COME_ON			26501	// 「Come On!」
#define CG_ICON_GO				26502	// 「Go!」
#define CG_ICON_WATCHING		26503	// 「Watching」
#define CG_ICON_MISS			26504	// 「Miss...」
#define CG_ICON_FAIL			26505	// 「Fail...」
#define CG_ICON_GET				26506	// 「Get!!」
#define CG_ICON_COUNTER			26507	// 「Counter!」
#define CG_ICON_DANGER			26508	// 「Danger!」
#define CG_ICON_NO				26509	// 「No!」
#define CG_ICON_GUARD			26510	// 「Guard!」
#define CG_ICON_ESCAPE  		26511	// 「Escape!」
#define CG_ICON_CAPTURE 		26512	// 「Capture!」
#define CG_ICON_LEAVE			26513	// 「Leave!」
#define CG_ICON_GUARD_BREAK 	26514	// 「Guard Break!」
#define CG_ICON_CRUSH		 	26515	// 「Crush!」
#define CG_ICON_CAPTURE_UP	 	26516	// 「Capture Up!」

// ペットの顔無しグラフィック  宠物的脸无图形
#define CG_NOW_PAINTING			28999

// タイトル  标题
#define CG_LOGO				29000
#define CG_TITLE			29001
#define CG_TITLE_NAME_S		29002
#define CG_TITLE_NAME_T		29003
#define CG_TITLE_NAME_O 	29004
#define CG_TITLE_NAME_N		29005
#define CG_TITLE_NAME_E		29006
#define CG_TITLE_NAME_A		29007
#define CG_TITLE_NAME_G		29008
#define CG_TITLE_NAME_E2	29009
#define CG_TITLE_NAME		29010
#define CG_TITLE_NAME_FLASH		29011
#define CG_TITLE_NAME_FLASH1	29012
#define CG_TITLE_NAME_FLASH2	29013
#define CG_TITLE_NAME_FLASH3	29014
#define CG_TITLE_NAME_FLASH4	29015
#define CG_TITLE_NAME_FLASH5	29016
#define CG_TITLE_JSS_LOGO		29017
#define CG_TITLE_DREAM_LOGO		29018
#define CG_TITLE_NOW_LOADING	29019
#define CG_TITLE_ID_PASS		29020
#define CG_TITLE_ID_PASS_OK		29021
#define CG_TITLE_ID_PASS_QUIT	29022

// キャラ作成 角色作成 包含物件
#define CG_CHR_MAKE_SEL_BG		29030		// 新規キャラ選択画面  新角色选择画面29030
#define CG_CHR_MAKE_BG			29031		// 新規キャラパラメータ振り分け画面
#define CG_CHR_SEL_BG			29032		// キャラクタ選択画面
#define CG_CHR_SEL_LOGIN_BTN	29033		// ログインボタン
#define CG_CHR_SEL_NEW_BTN		29034		// 新規ボタン
#define CG_CHR_SEL_DEL_BTN		29035		// 削除ボタン
#define CG_CHR_SEL_BACK_BTN		29036		// 戻るボタン
#define CG_CHR_MAKE_OK_BTN		29037		// 新規キャラ 決定ボタン
#define CG_CHR_MAKE_BACK_BTN	29038		// 新規キャラ 戻るボタン
#define CG_CHR_MAKE_SEL2_BG		29039		// 出身地選択画面
#define CG_CHR_MAKE_HOME_NAME0	29040		// 出身地名「サムギルの村」
#define CG_CHR_MAKE_HOME_NAME1	29041		// 出身地名「マリナスの村」
#define CG_CHR_MAKE_HOME_NAME2	29042		// 出身地名「ジャジャの村」
#define CG_CHR_MAKE_HOME_NAME3	29043		// 出身地名「カルターナの村」
#define CG_CHR_MAKE_EYE_SEL		29044		// 新規キャラ 目?口選択
#define CG_CHR_MAKE_NOSE_SEL	29045		// 新規キャラ 鼻?口選択
#define CG_CHR_MAKE_FACE		30000		// キャラ顔画像開始

#endif

