



// パレットファイルネーム
"data\\pal\\Palet_1.sap",	// 昼
"data\\pal\\Palet_2.sap",	// 夕方
"data\\pal\\Palet_3.sap",	// 夜
"data\\pal\\Palet_4.sap",	// 朝

"data\\pal\\Palet_5.sap",	// 地属性
"data\\pal\\Palet_6.sap",	// 水属性
"data\\pal\\Palet_7.sap",	// 火属性
"data\\pal\\Palet_8.sap",	// 風属性
"data\\pal\\Palet_9.sap",	// 赤
"data\\pal\\Palet_10.sap",	// マゼンタ
"data\\pal\\Palet_11.sap",	// シアン
"data\\pal\\Palet_12.sap",	// 紫
"data\\pal\\Palet_13.sap",	// 青
"data\\pal\\Palet_14.sap",	// 緑
"data\\pal\\Palet_15.sap",	// 黄

